[build]
  # Publish directory (where your static files are)
  publish = "."
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Build environment variables (if needed)
  NODE_VERSION = "18"

# Secrets scanning configuration
[build.processing.secrets]
  # Omit specific keys that appear in URLs/domains (not actual secrets)
  # N8N_USERNAME is "salesgenius" which appears in many URLs/domains
  # N8N_WEBHOOK_URL is a public URL, not a secret
  omit_keys = ["N8N_USERNAME", "N8N_WEBHOOK_URL"]

